### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by davidmuchow** [camden-git/romi-docs#2]
hey guys! 
great job on creating some resources for the team; we are in desperate need of romi advice.
i just noticed your [arm page](https://github.com/camden-git/romi-docs/blob/main/arm.md) said this: 
"For isFinished you can just make it return false, it's weird."

isFinished() is a method that the command scheduler calls to determine whether or not the command should end. when isFinished() returns false, it is perpetual: it does not end (unless it is cancelled because another command that is scheduled requires the same subsystem.)
 
keep going! thank you for writing docs for the team.

**Comment by camden-git** [comment]
thanks ill add that to the next update

**Comment by camden-git** [comment]
i did it
